// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACxeZ9yuo8c9LZRcb5vb0X3Jfz28JyO6M',
    appId: '1:148370820587:web:725c5d6902001ffd9a1dae',
    messagingSenderId: '148370820587',
    projectId: 'document-manager-b2ed0',
    authDomain: 'document-manager-b2ed0.firebaseapp.com',
    storageBucket: 'document-manager-b2ed0.firebasestorage.app',
    measurementId: 'G-B2B25N6E60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnnj8pNIzmMuLCY9SpVxpG_0kpO951iE0',
    appId: '1:148370820587:android:eb852c62f53f814f9a1dae',
    messagingSenderId: '148370820587',
    projectId: 'document-manager-b2ed0',
    storageBucket: 'document-manager-b2ed0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFgMDFnit9Tun3vvWJ4UeUCU7uP8gN96w',
    appId: '1:148370820587:ios:a1cf4ac1df980f349a1dae',
    messagingSenderId: '148370820587',
    projectId: 'document-manager-b2ed0',
    storageBucket: 'document-manager-b2ed0.firebasestorage.app',
    iosBundleId: 'com.example.secureDocumentManager',
  );
}
